export const FDC3_2_0_TOPICS = {
  DROP_CONTEXT_LISTENER: 'FDC3_2.0:dropContextListener',
  ADD_CONTEXT_LISTENER: 'FDC3_2.0:addContextListener',
  DROP_INTENT_LISTENER: 'FDC3_2.0:dropIntentListener',
  ADD_INTENT_LISTENER: 'FDC3_2.0:addIntentListener',
  BROADCAST: 'FDC3_2.0:broadcast',
  OPEN: 'FDC3_2.0:open',
  CONTEXT: 'FDC3_2.0:context',
  GET_CURRENT_CONTEXT: 'FDC3_2.0:getCurrentContext',
  GET_OR_CREATE_CHANNEL: 'FDC3_2.0:getOrCreateChannel',
  GET_SYSTEM_CHANNELS: 'FDC3_2.0:getSystemChannels',
  GET_USER_CHANNELS: 'FDC3_2.0:getUserChannels',
  LEAVE_CURRENT_CHANNEL: 'FDC3_2.0:leaveCurrentChannel',
  GET_CURRENT_CHANNEL: 'FDC3_2.0:getCurrentChannel',
  JOIN_CHANNEL: 'FDC3_2.0:joinChannel',
  JOIN_USER_CHANNEL: 'FDC3_2.0:joinUserChannel',
  INTENT: 'FDC3_2.0:intent',
  FIND_INTENT: 'FDC3_2.0:findIntent',
  FIND_INTENTS_BY_CONTEXT: 'FDC3_2.0:findIntentsByContext',
  RAISE_INTENT: 'FDC3_2.0:raiseIntent',
  RESOLVE_INTENT: 'FDC3_2.0:resolveIntent',
  RAISE_INTENT_FOR_CONTEXT: 'FDC3_2.0:raiseIntentForContext',
};
