import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "how-to-consume",
    "run-sail",
    "add-your-app",
    "getting-started",
    {
      type: "category",
      label: "Architecture",
      items: [
        "architecture/overview",
        "architecture/security",
        "architecture/deployment-targets",
        "architecture/channel-selection",
      ],
    },
    {
      type: "category",
      label: "Packages",
      items: [
        {
          type: "category",
          label: "@finos/sail-desktop-agent",
          items: [{ type: "autogenerated", dirName: "packages/desktop-agent" }],
        },
        "packages/platform/overview",
        "packages/sail-finance/overview",
        "packages/sail-finance/panel-architecture",
        "packages/sail-one/overview",
        "packages/sail-theme/overview",
        "packages/conformance-harness/overview",
      ],
    },
    "development",
  ],
}

export default sidebars
