export const RUNTIME_TOPICS = {
  TAB_SELECTED: 'runtime:tabSelected',
  TAB_DRAG_START: 'runtime:tabDragStart',
  NEW_TAB: 'runtime:newTab',
  ADD_TAB: 'runtime:addTab',
  DROP_TAB: 'runtime:dropTab',
  SELECT_TAB: 'runtime:selectTab',
  TEAR_OUT_TAB: 'runtime:tearOutTab',
  CLOSE_TAB: 'runtime:closeTab',
  REMOVE_TAB: 'runtime:removeTab',
  FETCH_FROM_DIRECTORY: 'runtime:fetchFromDirectory',
  OPEN_TOOLS_MENU: 'runtime:openToolsMenu',
  WINDOW_START: 'runtime:windowStart',
  OPEN_CHANNEL_PICKER: 'runtime:openChannelPicker',
  JOIN_WORKSPACE_TO_CHANNEL: 'runtime:joinWorkspaceToChannel',
  CHANNEL_SELECTED: 'runtime:channelSelected',
  HIDE_WINDOW: 'runtime:hideWindow',
  HIDE_RESULTS_WINDOW: 'runtime:hideResultsWindow',
  SEARCH: 'runtime:search',
  SEARCH_LOAD_RESULTS: 'runtime:loadSearchResults',
  RES_LOAD_RESULTS: 'runtime:loadResolverResults',
  RES_RESOLVE_INTENT: 'runtime:resolveIntent',
};
